# Sourced/run by kernel.nix's postPatch via the build shell; no shebang,
# because the Nix sandbox has no /usr/bin/env.
# Graft this port's out-of-tree bits into a kernel source tree.
#
# Called from kernel.nix's postPatch. This exists instead of a checked-in
# .patch file because that patch had to be regenerated by hand every time the
# driver changed, and twice this port shipped a stale one: the source and the
# patch disagreed, and the build silently used the old code. The .c file is
# now the single source of truth.
#
# Nothing here introduces a Kconfig symbol. An option would have to exist when
# nixpkgs generates .config, which happens in a separate derivation that only
# sees kernelPatches, not postPatch. The driver is a few kilobytes and does
# nothing unless the zumapro_bootfb parameter is passed, so it is simply
# always built in.
set -euo pipefail

src="$1"     # directory holding zumapro-bootfb.c
dts="$2"     # directory holding the device tree sources

# --- device tree ---------------------------------------------------------
install -m444 "$dts"/zumapro.dtsi \
              "$dts"/zumapro-pixel-common.dtsi \
              "$dts"/zumapro-tegu.dts \
              arch/arm64/boot/dts/exynos/google/
printf 'dtb-$(CONFIG_ARCH_EXYNOS) += zumapro-tegu.dtb\n' \
	>> arch/arm64/boot/dts/exynos/google/Makefile

# --- boot framebuffer driver --------------------------------------------
install -m444 "$src"/zumapro-bootfb.c drivers/video/zumapro-bootfb.c
printf 'obj-y += zumapro-bootfb.o\n' >> drivers/video/Makefile

# --- simplefb: name the channel order this bootloader hands over ---------
# The Pixel bootloader leaves a BGRA8888 buffer scanning out. simplefb has no
# name for that order, so without this the framebuffer has to be described
# inaccurately and the console renders with red and blue swapped. Alpha is
# meaningless for a scanout-only layer, so BGRX8888 is the honest description
# and DRM can already convert into it.
hdr=include/linux/platform_data/simplefb.h
anchor='DRM_FORMAT_ABGR8888'
if ! grep -q "$anchor" "$hdr"; then
	echo "apply.sh: no $anchor in $hdr; the format table moved upstream" >&2
	exit 1
fi
if grep -q b8g8r8x8 "$hdr"; then
	echo "apply.sh: upstream now defines b8g8r8x8; drop this hunk" >&2
	exit 1
fi
sed -i "/$anchor/a\\	{ \"b8g8r8x8\", 32, {8, 8}, {16, 8}, {24, 8}, {0, 0}, DRM_FORMAT_BGRX8888 }, \\\\" "$hdr"
grep -q b8g8r8x8 "$hdr" || { echo "apply.sh: simplefb edit did not apply" >&2; exit 1; }
