# Sourced/run by kernel.nix's postPatch via the build shell; no shebang,
# because the Nix sandbox has no /usr/bin/env.
# Graft this port's out-of-tree bits into a kernel source tree.
#
# Called from kernel.nix's postPatch. This exists instead of a checked-in
# .patch file because that patch had to be regenerated by hand every time the
# driver changed, and twice this port shipped a stale one: the source and the
# patch disagreed, and the build silently used the old code. The .c file is
# now the single source of truth.
#
# Nothing here introduces a Kconfig symbol. An option would have to exist when
# nixpkgs generates .config, which happens in a separate derivation that only
# sees kernelPatches, not postPatch. The driver is a few kilobytes and does
# nothing unless the zumapro_bootfb parameter is passed, so it is simply
# always built in.
set -euo pipefail

src="$1"     # directory holding zumapro-bootfb.c
dts="$2"     # directory holding the device tree sources

# --- device tree ---------------------------------------------------------
install -m444 "$dts"/zumapro.dtsi \
              "$dts"/zumapro-pixel-common.dtsi \
              "$dts"/zumapro-tegu.dts \
              arch/arm64/boot/dts/exynos/google/
printf 'dtb-$(CONFIG_ARCH_EXYNOS) += zumapro-tegu.dtb\n' \
	>> arch/arm64/boot/dts/exynos/google/Makefile

# --- boot framebuffer driver --------------------------------------------
install -m444 "$src"/zumapro-bootfb.c drivers/video/zumapro-bootfb.c
printf 'obj-y += zumapro-bootfb.o\n' >> drivers/video/Makefile

# --- simplefb: name the channel order this bootloader hands over ---------
# The Pixel bootloader leaves a BGRA8888 buffer scanning out. simplefb has no
# name for that order, so without this the framebuffer has to be described
# inaccurately and the console renders with red and blue swapped. Alpha is
# meaningless for a scanout-only layer, so BGRX8888 is the honest description
# and DRM can already convert into it.
# --- clocks: minimal CMU_HSI2 for this SoC -------------------------------
# Tensor G4 has no mainline clock driver. UFS cannot come up without one, so
# this adds just the HSI2 gates it needs. See the file for the register data
# and why gs101's driver cannot be reused at a different base address.
install -m444 "$src"/clk-zumapro-hsi2.c drivers/clk/samsung/clk-zumapro-hsi2.c
printf 'obj-y\t+= clk-zumapro-hsi2.o\n' >> drivers/clk/samsung/Makefile

# --- UFS pins: restore what the bootloader parked ------------------------
# Measured: the bootloader switches the UFS device's VCC rail off (gpp0[1])
# and parks the reference clock output (gph5[0]) as a low GPIO. A bring-up
# shim until this SoC has a pinctrl driver; see the file for why it cannot
# be done from userspace.
install -m644 "$src"/zumapro-ufs-restore.c drivers/soc/samsung/zumapro-ufs-restore.c
printf 'obj-y\t+= zumapro-ufs-restore.o\n' >> drivers/soc/samsung/Makefile

# --- UFS PHY: Tensor G4 variant -----------------------------------------
python3 "$src"/add-zumapro-ufs-phy.py

# --- UFS host controller: report clock-stop state before calibration -----
# Diagnostic. The PHY takes our register writes but never finishes
# calibrating, so print whether the M-PHY reference clock is actually
# running at that moment instead of assuming ungate_clks did its job.
python3 "$src"/dump-ufs-clkstop.py

# --- UFS PHY: option to keep the bootloader's configuration --------------
# Measured: the bootloader leaves every UFS clock running and reads the
# kernel off UFS, so its PHY state works. This adds a switch to skip the
# PRE_INIT calibration table and test whether overwriting it is the bug.
python3 "$src"/keep-boot-phy.py

# --- UFS PMA: snapshot the register space around the calibration trigger -
# Diagnostic. Establishes whether the analogue block does anything at all
# when the trigger is written; every earlier probe only sampled registers
# chosen in advance. Must run after keep-boot-phy.py, whose anchor it uses.
python3 "$src"/pma-dump.py

# --- UFS: dump the register regions this port does not map ---------------
# The PMA register file answers but nothing executes behind it, so whatever
# gates the engine is outside the PHY. vs_hci is mapped here at 1/16th of
# its stock size and has never been looked at. Read-only.
python3 "$src"/region-dump.py

# --- UFS: trace HCS through init ----------------------------------------
# The bootloader hands over HCS=0x10f: device present, lists ready, link up.
# By first probe it is 0. Find which step tears it down.
python3 "$src"/hcs-trace.py

hdr=include/linux/platform_data/simplefb.h
anchor='DRM_FORMAT_ABGR8888'
if ! grep -q "$anchor" "$hdr"; then
	echo "apply.sh: no $anchor in $hdr; the format table moved upstream" >&2
	exit 1
fi
if grep -q b8g8r8x8 "$hdr"; then
	echo "apply.sh: upstream now defines b8g8r8x8; drop this hunk" >&2
	exit 1
fi
sed -i "/$anchor/a\\	{ \"b8g8r8x8\", 32, {8, 8}, {16, 8}, {24, 8}, {0, 0}, DRM_FORMAT_BGRX8888 }, \\\\" "$hdr"
grep -q b8g8r8x8 "$hdr" || { echo "apply.sh: simplefb edit did not apply" >&2; exit 1; }
