#!/usr/bin/env bash
# Build a bring-up ramdisk for the Pixel 9a (tegu).
#
# Established on hardware so far:
#   * GKI layout: boot=kernel, init_boot=generic ramdisk, vendor_kernel_boot=DTB+modules.
#     Replacing the init_boot ramdisk puts our /init in charge.
#   * cmdline has `console=ttynull` first and `console=ttySAC0` last; ttynull
#     registers as `ttynull0`, so /dev/console is a black hole.
#   * No devtmpfs: every device node must be created by hand.
#   * /dev/kmsg reaches the UART via printk - the reliable output channel.
#   * After enabling uart@10870000 in the DTB the platform device 10870000.uart
#     appears, but *no driver binds to it* and many unrelated devices sit in
#     "deferred probe pending" (disp-vddd, fixedregulator@0, gpio_keys,
#     gs-drm-connector). That is the signature of missing supplier modules, so
#     this build loads Android's own modules.load in full (with a retry pass)
#     instead of a hand-picked subset, and reports devices_deferred to prove it.
set -euo pipefail

OUT_DIR="${OUT_DIR:-/home/max/android/tegu/m1}"
WORK="${WORK:-/home/max/pixel9a-work/m1}"
BUSYBOX="${BUSYBOX:-}"

if [ -z "$BUSYBOX" ]; then
  echo "[build] resolving static aarch64 busybox"
  BUSYBOX="$(nix build --no-link --print-out-paths \
    'nixpkgs#legacyPackages.x86_64-linux.pkgsCross.aarch64-multiplatform.pkgsStatic.busybox')/bin/busybox"
fi
[ -x "$BUSYBOX" ] || { echo "[build] busybox not executable: $BUSYBOX" >&2; exit 1; }
echo "[build] busybox: $BUSYBOX ($(stat -c%s "$BUSYBOX") bytes)"

mkdir -p "$OUT_DIR"
rm -rf "$WORK"; mkdir -p "$WORK/root"/{bin,dev,proc,sys,etc,tmp,mnt,lib/modules}
install -m 0755 "$BUSYBOX" "$WORK/root/bin/busybox"

cat > "$WORK/root/init" <<'INIT'
#!/bin/busybox sh
/bin/busybox --install -s /bin 2>/dev/null

B="[TEGU-M1]"
mkdir -p /proc /sys /dev /tmp /mnt /sys/kernel/debug

[ -c /dev/kmsg ] || mknod -m 600 /dev/kmsg c 1 11 2>/dev/null
kmsg() { echo "TEGU-M1: $*" > /dev/kmsg 2>/dev/null; }
kout() { echo "TEGU-OUT: $*" > /dev/kmsg 2>/dev/null; }

kmsg "init: v8 executing (uid=$(id -u))"
mount -t proc   proc   /proc 2>/dev/null
mount -t sysfs  sysfs  /sys  2>/dev/null
mount -t devtmpfs devtmpfs /dev 2>/dev/null
mount -t debugfs debugfs /sys/kernel/debug 2>/dev/null
[ -c /dev/null ] || mknod -m 666 /dev/null c 1 3 2>/dev/null
[ -c /dev/zero ] || mknod -m 666 /dev/zero c 1 5 2>/dev/null
[ -c /dev/tty ]  || mknod -m 666 /dev/tty  c 5 0 2>/dev/null
[ -c /dev/mem ]  || mknod -m 600 /dev/mem  c 1 1 2>/dev/null

dev_of() {
  mm=$(cat "/sys/class/tty/$1/dev" 2>/dev/null)
  [ -n "$mm" ] || mm=$(awk -v c="$1" '$1==c {print $NF}' /proc/consoles 2>/dev/null)
  echo "$mm"
}
deferred() { tr '\n' ' ' < /sys/kernel/debug/devices_deferred 2>/dev/null; }

# ---- device tree status -----------------------------------------------------
DT=/sys/firmware/devicetree/base
N="$DT/uart@10870000"
kmsg "dt: uart status='$(tr -d '\000' < "$N/status" 2>/dev/null)' compatible='$(tr -d '\000' < "$N/compatible" 2>/dev/null)'"
kmsg "dt: node present=$([ -d "$N" ] && echo yes || echo no) debugfs=$([ -d /sys/kernel/debug ] && echo yes || echo no)"
kmsg "pre: deferred = $(deferred)"

# ---- shells (only meaningful once a tty exists) -----------------------------
SHELLS_STARTED=""
start_shells() {
  CANDS=""
  for c in $(awk '{print $1}' /proc/consoles 2>/dev/null); do
    case "$c" in ttynull*|ramoops*) continue ;; esac
    CANDS="$CANDS $c"
  done
  for c in $(ls /sys/class/tty 2>/dev/null | grep -E '^ttySAC'); do CANDS="$CANDS $c"; done
  for c in $CANDS; do
    mm=$(dev_of "$c"); case "$mm" in *:*) ;; *) continue ;; esac
    [ -c "/dev/$c" ] || mknod -m 600 "/dev/$c" c "${mm%%:*}" "${mm##*:}" 2>/dev/null
    [ -c "/dev/$c" ] || continue
    case " $SHELLS_STARTED " in *" $c "*) continue ;; esac
    SHELLS_STARTED="$SHELLS_STARTED $c"
    kmsg "shell: spawn on /dev/$c ($mm)"
    setsid /bin/sh -c "echo; echo '$B console shell on /dev/$c'; echo; exec /bin/sh -i" \
        < "/dev/$c" > "/dev/$c" 2>&1 &
  done
}

# ---- load Android's full module list, twice --------------------------------
# The vendor modules ship flat in /lib/modules with modules.dep/load generated by
# Android. Insmod-in-order plus one retry pass mirrors what Android's init does
# and lets supplier modules (clocks, PMIC, regulators) land before their
# consumers, which is what the deferred probes are waiting on.
ML=/lib/modules/modules.load
LOADED=/tmp/.loaded; FAILED=/tmp/.failed
: > "$LOADED"; : > "$FAILED"
pass() {
  while read -r m; do
    [ -n "$m" ] || continue
    case "$m" in \#*) continue ;; esac
    [ -f "/lib/modules/$m" ] || continue
    grep -qx "$m" "$LOADED" 2>/dev/null && continue
    insmod "/lib/modules/$m" 2>/dev/null
    rc=$?
    if [ $rc -eq 0 ] || [ $rc -eq 17 ]; then
      echo "$m" >> "$LOADED"
    else
      echo "$m|$rc" >> "$FAILED"
    fi
  done < "$ML"
}
pass
kmsg "mod: pass1 loaded=$(wc -l < $LOADED) failed=$(wc -l < $FAILED)"
: > "$FAILED"
pass
kmsg "mod: pass2 failed=$(wc -l < $FAILED)"

kmsg "console: ttySAC count=$(ls /sys/class/tty 2>/dev/null | grep -c '^ttySAC') dev='$(dev_of ttySAC0)'"
kmsg "console: bound=$([ -e /sys/bus/platform/devices/10870000.uart/driver ] && echo yes || echo no)"
kmsg "console: consoles=$(tr '\n' '|' < /proc/consoles 2>/dev/null)"
start_shells

kmsg "post: deferred = $(deferred)"
kmsg "post: drm = $(ls /sys/class/drm 2>/dev/null | tr '\n' ' ')"
dmesg 2>/dev/null | grep -iE 'ttySAC|10870000|samsung-uart|exynos-uart' | tail -12 | while IFS= read -r l; do kmsg "dmesg: $l"; done
kmsg "init: loaded=$(wc -l < $LOADED) failed=$(tr '\n' ' ' < $FAILED)"
kmsg "init: READY"

# ---- /dev/mem fallback command channel -------------------------------------
# Only if no tty appeared. Reports its own failure honestly.
UART=0x10870000
mem_console() {
  [ -c /dev/mem ] || { kmsg "mem: /dev/mem node missing"; return 1; }
  err=$(dd if=/dev/mem bs=1 skip=$((UART + 0x10)) count=4 2>&1 >/dev/null)
  st=$(dd if=/dev/mem bs=1 skip=$((UART + 0x10)) count=4 2>/dev/null | od -An -tu4 | tr -d ' ')
  if [ -z "$st" ]; then kmsg "mem: /dev/mem read failed: $err"; return 1; fi
  kmsg "mem: UART via /dev/mem OK (UTRSTAT=$st) - command channel live"
  kout "=== tegu command channel: type a command + Enter ==="
  line=""
  while :; do
    st=$(dd if=/dev/mem bs=1 skip=$((UART + 0x10)) count=4 2>/dev/null | od -An -tu4 | tr -d ' ')
    if [ -n "$st" ] && [ $((st & 1)) -ne 0 ]; then
      d=$(dd if=/dev/mem bs=1 skip=$((UART + 0x24)) count=4 2>/dev/null | od -An -tu4 | tr -d ' ')
      case "$d" in
        13|10)
          if [ -n "$line" ]; then
            kmsg "repl: \$ $line"
            sh -c "$line" 2>&1 | while IFS= read -r l; do kout "$l"; done
            kout "--- end ---"
            line=""
          fi ;;
        127|8) line="${line%?}" ;;
        *) line="$line$(printf "\\$(printf '%03o' $(( ${d:-0} & 255 )))")" ;;
      esac
    else
      sleep 0.03
    fi
  done
}
mem_console &

# Heartbeat through kmsg so liveness is always observable.
( while :; do kmsg "alive uptime=$(cut -d' ' -f1 /proc/uptime)s"; sleep 30; done ) &

while :; do sleep 3600; done
INIT
chmod 0755 "$WORK/root/init"

echo "[build] packing initramfs"
( cd "$WORK/root" && find . | cpio -o -H newc --quiet ) > "$WORK/initramfs.cpio"
lz4 -l -f "$WORK/initramfs.cpio" "$WORK/initramfs.lz4" >/dev/null
magic=$(head -c4 "$WORK/initramfs.lz4" | od -An -tx1 | tr -d ' \n')
echo "[build] cpio=$(stat -c%s "$WORK/initramfs.cpio") lz4=$(stat -c%s "$WORK/initramfs.lz4") magic=0x$magic"

echo "[build] building init_boot.img"
mkbootimg --header_version 4 --ramdisk "$WORK/initramfs.lz4" \
  --os_version 16.0.0 --os_patch_level 2026-09 -o "$OUT_DIR/init_boot.img"
unpack_bootimg --boot_img "$OUT_DIR/init_boot.img" --out "$WORK/verify" 2>&1 | sed 's/^/      /'
echo "[build] done -> $OUT_DIR/init_boot.img"
